[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "true"

[build.production.environment]
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200